### ISSUE TITLE
FactoryTest for Lora 32 v2 doesn't work.

### ISSUE THREAD

**Issue by tavdog** [HelTecAutomation/Heltec_ESP32#6]
I have two Lora V2 boards.  They do work with some sketches but the factory ping pong test does not work.  The factory test DID work out of the box, but once flashed with the example code here, both boards fail to receive any packets.  They send the packets but do not receive.

**Comment by Heltec-Aaron-Lee** [comment]
Hi @tavdog 
did you install the newest [Heltec ESP32 develop environment](https://docs.heltec.cn/#/en/user_manual/how_to_install_esp32_Arduino)?

![图片](https://user-images.githubusercontent.com/32860565/54739218-4d25c300-4bf2-11e9-895f-584038e330d5.png)
Also you need config here to the RF band you need. I think 868E6 is fine for you.

**Comment by stefkpl** [comment]
Try to add under Heltec.begin( .....

```
  Heltec.display->init();
  Heltec.display->flipScreenVertically();  
  Heltec.display->setFont(ArialMT_Plain_10);
```
I send a merge request today.

**Comment by tavdog** [comment]
Why would adding display commands fix the RF sending problems ?  I am still having problems with the heltec boards.  They won't transmit after a receive.  If software reset then transmitting works again.

**Comment by stefkpl** [comment]
Sorry, it's mistake, my reply was for the other post :(
I use Arduino IDE with the serial monitor. In this case, you can see errors from your board.

**Comment by Heltec-Aaron-Lee** [comment]
@tavdog We released V1.0.5 library with LoRa bug fix, did you try this new version?

**Comment by tavdog** [comment]
I have tried the new version. The FactoryTest example still does NOT work.  The OLED Lora Receive / Transmit examples DO work.

**Comment by Heltec-Aaron-Lee** [comment]
@tavdog Oh, how come... I will test it now

**Comment by tavdog** [comment]
The Lora part of the FactoryTestLora is working but the received packets are only showing in the serial output, not on the OLED screen.

**Comment by solotaker** [comment]
> The Lora part of the FactoryTestLora is working but the received packets are only showing in the serial output, not on the OLED screen.

Sorry, I fixed this problem, and now the example works fine. The reason for the problem is because there were some errors in the previous code submission.
